### ISSUE TITLE
Ogaben ER

### ISSUE THREAD

**Issue by dimes123** [Kriznar4/the_real_skladisce#1]
Zakaj imata tako ogaben ER diagram?

**Comment by Kriznar4** [comment]
Očitno nekdo nima smisla za estetiko!

**Comment by Kriznar4** [comment]
Poglej ER diagram sedaj. Bolje?

**Comment by dimes123** [comment]
10/10 would visit again

**Comment by Kriznar4** [comment]
Odlično :+1:
